keys:
  # Users
  - &users:
    - &hyshka 24F4192528C48797E539F247DB2D93D1BFAAA6EA
  # Hosts
  - &hosts:
    # generate age from ssh host key
    # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    # when changing keys
    # sops --config ./.sops.yaml updatekeys ./starship/secrets.yaml
    - &starship age1sl93uhtzglmcyq2zuk76ndfh9k95mnhdcsdjt6a5sjr069c4ep9sjwna3p
    - &rpi4 age12sle9vz3zh5kcw62g4l0azn2keq0a3s46g35628rw9za7nd3x4pq7uen2l
    - &tiny1 age1c6wsp9h35dzzy8m2rk2y2agj0jvfadsfsdl2vaf4y00zhlxtdskqx9kh6x
    - &ashyn age1sc6hmzhpfdtr6ee6s3yh0xa947hn8gd9v3gzs0wkakrsauef0qtqetunfd
    # not easy to find ssh host key on macos
    # age-keygen -o ~/.config/sops/age/keys.txt
    - &macpro age19p5rdffzshspj0gcqf7sls5r3klnjcjdhd6qdcuvsqap5pu2h38sqrzv6l

creation_rules:
  - path_regex: hosts/starship/secrets.ya?ml$
    key_groups:
      - age:
          - *starship
        pgp:
          - *hyshka
  - path_regex: hosts/rpi4/secrets.ya?ml$
    key_groups:
      - age:
          - *rpi4
        pgp:
          - *hyshka
  - path_regex: hosts/tiny1/secrets.ya?ml$
    key_groups:
      - age:
          - *tiny1
        pgp:
          - *hyshka
  - path_regex: hosts/ashyn/secrets.ya?ml$
    key_groups:
      - age:
          - *ashyn
        pgp:
          - *hyshka
  - path_regex: home-manager/secrets.ya?ml$
    key_groups:
      - age:
          - *starship
          - *macpro
          - *tiny1
          - *ashyn
        pgp:
          - *hyshka

  #- path_regex: hosts/common/secrets.ya?ml$
  #      key_groups:
  #      - age:
  #        - *starship
  #        pgp:
  #        - *hyshka
