keys:
  # Users
  - &users:
    - &hyshka 24F4192528C48797E539F247DB2D93D1BFAAA6EA
  # Hosts
  - &hosts:
    # generate age from ssh host key
    # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    # when changing keys
    # sops --config ./.sops.yaml updatekeys ./starship/secrets.yaml
    - &starship age1sl93uhtzglmcyq2zuk76ndfh9k95mnhdcsdjt6a5sjr069c4ep9sjwna3p
    - &rpi4 age12sle9vz3zh5kcw62g4l0azn2keq0a3s46g35628rw9za7nd3x4pq7uen2l
    - &tiny1 age1c6wsp9h35dzzy8m2rk2y2agj0jvfadsfsdl2vaf4y00zhlxtdskqx9kh6x
    - &ashyn age14nj99csleyr6sxpv4t3j77586uzaq90264p7hp2fz8w2gen6na8sc7fpg7
    - &lxc-paperless age10xhslkeewm6ltp7fz5rxecjsscj6nj27xc0xkxeekzn8sv63nf2srv6yld
    - &lxc-immich age14vd6j6zclech4c942awwcn0hq6gz824hlpt2pwzel3qh3r7v4g2qlwmunz
    # not easy to find ssh host key on macos
    # age-keygen -o ~/.config/sops/age/keys.txt
    - &macpro age19p5rdffzshspj0gcqf7sls5r3klnjcjdhd6qdcuvsqap5pu2h38sqrzv6l

creation_rules:
  - path_regex: hosts/starship/secrets.ya?ml$
    key_groups:
      - age:
          - *starship
        pgp:
          - *hyshka
  - path_regex: hosts/rpi4/secrets.ya?ml$
    key_groups:
      - age:
          - *rpi4
        pgp:
          - *hyshka
  - path_regex: hosts/tiny1/secrets.ya?ml$
    key_groups:
      - age:
          - *tiny1
        pgp:
          - *hyshka
  - path_regex: hosts/ashyn/secrets.ya?ml$
    key_groups:
      - age:
          - *ashyn
        pgp:
          - *hyshka
  - path_regex: hosts/tiny1/services/[^/]+\.(sqlite)$
    key_groups:
      - age:
          - *tiny1
        pgp:
          - *hyshka
  - path_regex: containers/secrets/paperless.ya?ml$
    key_groups:
      - age:
          - *lxc-paperless
        pgp:
          - *hyshka
  - path_regex: containers/secrets/immich.ya?ml$
    key_groups:
      - age:
          - *lxc-immich
        pgp:
          - *hyshka
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *starship
          - *macpro
          - *tiny1
          - *ashyn
        pgp:
          - *hyshka

  #- path_regex: hosts/common/secrets.ya?ml$
  #      key_groups:
  #      - age:
  #        - *starship
  #        pgp:
  #        - *hyshka
