services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - ./wireguard-config:/config
    ports:
      - 8080:8080
      - 8085:8085
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    dns:
      - 194.242.2.2
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:wireguard
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent-config:/config
      - /mnt/storage/mediacenter/torrents:/data/torrents
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:wireguard
    environment:
      - PUID=13010
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - ./sabnzbd-config:/config
      - /mnt/storage/mediacenter/usenet:/data/usenet
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - ./sonarr-config:/config
      - /mnt/storage/mediacenter:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13004
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - ./radarr-config:/config
      - /mnt/storage/mediacenter:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13009
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - ./prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ=America/Edmonton
    volumes:
      - ./jellyfin-config:/config
      - /mnt/storage/mediacenter/media:/data
    devices:
      # allow hardware acceleration
      # https://docs.linuxserver.io/images/docker-jellyfin#intel
      - /dev/dri:/dev/dri
    ports:
      - "8096:8096"
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 13007:13000
    volumes:
      - ./recyclarr-config:/config
    environment:
      - TZ=America/Edmonton
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    user: 13008:13000
    volumes:
      - ./jellyseer-config:/app/config
    environment:
      - TZ=America/Edmonton
    ports:
      - 5055:5055
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
