{
  imports = [
    ./calibre.nix
    ./docker.nix
    ./homepage.nix
    ./media
    ./ntfy.nix
    ./restic.nix
    ./samba.nix
    ./snapraid.nix
    ./syncthing.nix
    ./caddy.nix
    ./acme.nix
    #./nextcloud.nix
    ./grafana
    ./adguard-home.nix
    ./incus.nix
  ];
}
