name: Flake Checker

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/flake-checker-action@v12
        with:
          fail-mode: true
          send-statistics: false
