name: Flake Checker

on:
  schedule:
    - cron: '0 0 * * *' # runs daily
  workflow_dispatch:

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/flake-checker-action@v12
