name: Flake Lock Updater

on:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00
  workflow_dispatch:

jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: DeterminateSystems/update-flake-lock@v27
        with:
          pr-title: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
